"""add notes to vital signs

Revision ID: 1bc676c32b01
Revises: cecc8132b3aa
Create Date: 2026-08-28 15:59:37.451930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc676c32b01'
down_revision: Union[str, Sequence[str], None] = 'cecc8132b3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vital_signs', 'notes')
    # ### end Alembic commands ###
