"""remove unused vital columns

Revision ID: cecc8132b3aa
Revises: c27234917d8a
Create Date: 2026-08-28 12:26:15.294698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecc8132b3aa'
down_revision: Union[str, Sequence[str], None] = 'c27234917d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lab_results', 'recorded_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('lab_results', 'glucose')
    op.drop_column('lab_results', 'test_name')
    op.drop_column('lab_results', 'sodium')
    op.drop_column('lab_results', 'blood_ph')
    op.drop_column('lab_results', 'hemoglobin')
    op.drop_column('lab_results', 'notes')
    op.drop_column('lab_results', 'potassium')
    op.drop_column('vital_signs', 'oxygen_support')
    op.drop_column('vital_signs', 'blood_glucose')
    op.drop_column('vital_signs', 'consciousness_level')
    op.drop_column('vital_signs', 'height')
    op.drop_column('vital_signs', 'notes')
    op.drop_column('vital_signs', 'weight')
    op.drop_column('vital_signs', 'pain_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('pain_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('consciousness_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('blood_glucose', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('oxygen_support', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('potassium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('hemoglobin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('blood_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('sodium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('test_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('glucose', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('lab_results', 'recorded_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
